### ISSUE TITLE
Option for 250+ pages pdf's (paying is ok)

### ISSUE THREAD

**Issue by Minderer** [jc9108/dark-mode-pdf#3]
Hello

I have some textbook with almost 1000 pages. It would be nice to convert them to darkmode.

I'm fine with paying.

Kind regards,

**Comment by Minderer** [comment]
Btw, I just tried with a PDF with about 160 pages, and it did not seem to work, unfortunately.
`> spawn process exited with code 0
> loading...
> spawn process exited with code 1
> sending pdf to your downloads
> deleting your data from the server
> your data has been deleted from the server
> end 165758354244741
> |`

**Comment by j9108c** [comment]
> Hello
> 
> I have some textbook with almost 1000 pages. It would be nice to convert them to darkmode.
> 
> I'm fine with paying.
> 
> Kind regards,

unfortunately, even if you paid once, i will not be able to sustain upgrading the server in the long run. this web tool isnt really meant for really large pdfs like that.

you could split the pdf up using [this script](https://github.com/j9108c/scripts/tree/main/pdf-tools), convert each one, then combine them back using [this script](https://github.com/j9108c/scripts/tree/main/pdf-tools). or, you could download the source code, change the page limit, then run the app locally, assuming your pc can handle it.

if those are too tedious, i am happy to convert your textbooks for you on my own machine for free. you can message me on discord (https://discord.gg/2CYAekZDuA).
<br/>
<br/>
> Btw, I just tried with a PDF with about 160 pages, and it did not seem to work, unfortunately.
> 
> The file was not saved on my computer before it was deleted. It might be a local issue.

this might be the same issue as [this](https://github.com/j9108c/dark-mode-pdf/issues/2). ill work on an alternate solution (probably a queueing system) soon but in the meantime ive lowered the page limit again. when it's done, ill post an update on this issue.

**Comment by Minderer** [comment]
> > Hello
> > I have some textbook with almost 1000 pages. It would be nice to convert them to darkmode.
> > I'm fine with paying.
> > Kind regards,
> 
> unfortunately, even if you paid once, i will not be able to sustain upgrading the server in the long run. this web tool isnt really meant for really large pdfs like that.
> 
> you could split the pdf up using [this script](https://github.com/j9108c/scripts/tree/main/pdf-tools), convert each one, then combine them back using [this script](https://github.com/j9108c/scripts/tree/main/pdf-tools). or, you could download the source code, change the page limit, then run the app locally, assuming your pc can handle it.
> 
> if those are too tedious, i am happy to convert your textbooks for you on my own machine for free. you can message me on discord (doobi1#9108).
> 
> 
> 
> 
> > Btw, I just tried with a PDF with about 160 pages, and it did not seem to work, unfortunately.
> > The file was not saved on my computer before it was deleted. It might be a local issue.
> 
> this might be the same issue as [this](https://github.com/j9108c/dark-mode-pdf/issues/2). ill work on an alternate solution (probably a queueing system) soon but in the meantime ive lowered the page limit again. when it's done, ill post an update on this issue.

I downloaded it, so you can delete now!
By the way, I can not contact you on discord for some reason, that is why I write here.

**Comment by j9108c** [comment]
> I downloaded it, so you can delete now!
> By the way, I can not contact you on discord for some reason, that is why I write here.

okay. oh and its because i deleted the temp server i guess. i didnt know that prevents from dm'ing after.

**Comment by j9108c** [comment]
alright ive added a queueing system for more reliability but decided to keep the page limit at 100 after consideration of the server hardware limitations D:

for larger pdfs, consider either using a script such as [this](https://github.com/j9108c/scripts/tree/main/pdf-tools) or other web tools such as [this](https://www.ilovepdf.com) to split and merge pdfs before and after converting them to dark mode

**Comment by j9108c** [comment]
alright ive added a queueing system for more reliability but decided to keep the page limit at 100 after consideration of the server hardware limitations D:

for larger pdfs, consider either using a script such as [this](https://github.com/j9108c/scripts/tree/main/pdf-tools) or other web tools such as [this](https://www.ilovepdf.com) to split and merge pdfs before and after converting them to dark mode
